targets:
  - name: webscraper-demo-list
    list_url: "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
    item_selector: "div.thumbnail"
    item_fields:
      title: "a.title@title"
      price: "h4.price"
      description: "p.description"
      image_url: "img@src"
      product_url: "a.title@href"
